### ISSUE TITLE
roadmap for a binary release and announcement

### ISSUE THREAD

**Issue by hannesm** [robur-coop/miragevpn#3]
- [ ] documentation of the different unikernels embedded in this repository
- [x] udp #1 
- [x] server #2 (not needed for a release)
- [x] more testing in different scenarios, especially in respect to authentication mechanisms (client certificates et al) #42 #43 #44 #45
- [ ] we authenticate the remote with CA (but no CRL :/), and there’s as well “verify-hash” for fingerprint auth, which we should support #34 #35
- [x] revive `app/openvpn_client_lwt.exe` #7
- [x] support `Remote_random` by randomizing remotes once at startup (done in #69)
- [ ] qubes integration (similar to qubes-mirage-firewall being able to act as netvm (IIUC) and dynamically get more client VMs whose traffic is routed (and encrypted) over the tunnel)

(please (esp @cfcs) extend by commenting on this issue or editing this task list if there's anything missing from the above list)

**Comment by cfcs** [comment]
[ ] documentation of supported subset of configuration options

**Comment by xbc5** [comment]
I'm wondering what the status is on Qubes support?

**Comment by hannesm** [comment]
there has been no further work on QubesOS support. from the packaging site, there is https://builds.robur.coop/job/openvpn-router/ that relies on [caravan](https://github.com/dinosaure/caravan/) as a post-link step to integrate the configuration into the image. (NB: This is a hvt image, but something similar could be done for a QubesOS openvpn client).

**Comment by hannesm** [comment]
I'm closing this laundry list of things. The major parts have been achieved, the issue tracker here contains other things. We should instead use a milestone and annotate the specific issues.

The remaining idea from here that I have not (yet) copied is the solo5 blob idea. The reason is that (a) it is not well specified (b) we can use the QubesDB on QubesOS, and a block device on solo5 (and/or boot parameters). If there are pressing issues, don't hesitate to open a fresh issue with one topic.
